### ISSUE TITLE
Feedback for Studio

### ISSUE THREAD

**Issue by LouisEiermann** [nuxtlabs/studio-demo#5]
Where are we supposed to leave feedback for Nuxt Studio?
Second question: My website is online on github pages with SSL with the alpine starter, see: https://www.buddha-natur.de/
But i can still not edit it on Nuxt Studio because there is the message 

"You must deploy your project to unlock live-preview and Studio features."

but it seems that i have done everything right no?

**Comment by Saganic** [comment]
Hi @LouisEiermann, if you have access to the private beta you should have been sent an invite to the Discord server. 

This is currently where feedback is being provided and reviewed. 

Have you followed the steps on [project set up documentation](https://nuxt.studio/docs/projects/setup)?

Ensure you have added the [verification token](https://nuxt.studio/docs/projects/setup#verification-token) `NUXT_PUBLIC_STUDIO_TOKENS` and that your project has the [@nuxthq/studio](https://www.npmjs.com/package/@nuxthq/studio) package installed.

**Comment by LouisEiermann** [comment]
I will continue on the discord, thanks!
